<program> ::= <function>* "int main()" <function_body>
<function> ::= <type> " " <identifier> "(" (<type> " " <identifier> ("," <type> " " <identifier>)*)? ")" <function_body>
<function_body> ::= "{" <declarations> <statements> "}"
<declarations> ::= { <declaration> }
<declaration> ::= <type> <identifier> ( "[" <integer> "]" )? ( "," <identifier> ( "[" <integer> "]" )? )* ";"
<statements> ::= { <statement> }
<statement> ::= ( ";" | <assignment> | <if_statement> | <while_loop> )
<assignment> ::= <identifier> ( "[" <expression> "]" )? "=" <expression> ";"
<if_statement> ::= "if" "(" <expression> ")" "{" <statements> "}" [ "else" "{" <statements> "}" ]
<while_loop> ::= "while" "(" <expression> ")" "{" <statements> "}"
<expression> ::= <conjunction> { "||" <conjunction> }
<conjunction> ::= <equality> { "&&" <equality> }
<equality> ::= <relation> ( ( "==" | "!=" ) <relation> )?
<relation> ::= <addition> ( ( "<" | "<=" | ">" | ">=" ) <addition> )?
<addition> ::= <term> { ( "+" | "-" ) <term> }
<term> ::= <factor> { ( "*" | "/" ) <factor> }
<factor> ::= ( "-" | "!" )? <primary>
<primary> ::= <identifier> ( "[" <expression> "]" )? | <literal> | "(" <expression> ")" | <function_call> | <type_cast>
<function_call> ::= <identifier> "(" ( <expression> ( "," <expression> )* )? ")"
<type_cast> ::= "(" <type> ")" <expression>
<type> ::= "int" | "float" | "char" | "bool"
<literal> ::= <integer_constant> | <float_constant> | <char_constant> | <bool_constant>
<integer_constant> ::= <digit>+
<float_constant> ::= <digit>+ "." <digit>+
<char_constant> ::= "'" <character> "'"
<bool_constant> ::= "true" | "false"
<identifier> ::= ( <letter> | "_" ) ( <letter> | <digit> | "_" )*
<character> ::= <letter> | <digit> | <special_character>
<special_character> ::= "+" | "-" | "*" | "/" | "=" | "<" | ">" | "!" | "&" | "|" | "%" | "^"
<digit> ::= "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9"
<letter> ::= "a" | "b" | ... | "z" | "A" | "B" | ... | "Z"
